services:
  mysql:
    image: 'mysql:8'
    container_name: mysql-cases
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '1313:3306'
    expose:
      - '1313'
    volumes:
      - './data:/var/lib/mysql'
